Location filter support
cognitedata/toolkit pull request #833
Opened 2024-08-19 13:18 UTC by ronpal

# Description

Adding support for location filters

## Checklist

- [x] Tests added/updated.
- [ ] Run Demo Job Locally.
- [ ] Documentation updated.
- [x] Changelogs updated in [CHANGELOG.cdf-tk.md](https://github.com/cognitedata/toolkit/blob/main/CHANGELOG.cdf-tk.md).
- [x] Template changelogs updated in [CHANGELOG.templates.md](https://github.com/cognitedata/toolkit/blob/main/CHANGELOG.templates.md).
- [x] Version bumped.
  [_version.py](https://github.com/cognitedata/toolkit/blob/main/cognite/cognite_toolkit/_version.py) and
  [pyproject.toml](https://github.com/cognitedata/toolkit/blob/main/pyproject.toml) per [semantic versioning](https://semver.org/).

2024-08-19 13:32 UTC, ronpal commented on cognite_toolkit/_cdf_tk/client/api/locations/location_filters.py
> +            data_set_id: Data set id of the LocationFilter.
This is just residue from copied code, will disappear 😇

2024-08-22 11:45 UTC, doctrino requested changes
Main feedback it to move the patching of the endpoint into the loader and not the client.

In addition, need to update the config for the ApprovalClient as well as implementing the `get_write_cls_parameter_spec` method in thhe loader.

2024-08-22 11:45 UTC, doctrino commented on cognite_toolkit/_cdf_tk/client/data_classes/locations.py
> +        externalId: The external ID provided by the client. Must be unique for the resource type.
```suggestion
        external_id: The external ID provided by the client. Must be unique for the resource type.
```

2024-08-22 11:45 UTC, doctrino commented on cognite_toolkit/_cdf_tk/client/data_classes/locations.py
> +class LocationFilterScene(DataModelId):
Why are you subclassing `DataModelI`? LocationFilterScene does not seem to be a type of data model id

2024-08-22 11:45 UTC, doctrino commented on cognite_toolkit/_cdf_tk/client/data_classes/locations.py
> +    asset_subtree_ids: list[dict[str, int | str]] | None = None
Hmm, maybe worth an special class her with identifier?
Alternative use a `Literal` .
```suggestion
    asset_subtree_ids: list[dict[Literal["id", "externalId"], int | str]] | None = None
```

2024-08-22 11:45 UTC, doctrino commented on cognite_toolkit/_cdf_tk/client/data_classes/locations.py
> +class LocationFilterAssetCentricBaseFilter:
Filter twice in the name, what about?
All nested classes of a `CogniteResource` should use `CogniteObject`
```suggestion
class AssetCentricSubFilter(CogniteObject):
```

2024-08-22 11:45 UTC, doctrino commented on cognite_toolkit/_cdf_tk/client/data_classes/locations.py
> +    asset_subtree_ids: list[dict[str, str]] | None = None
I am in favor of introducing a small class her Identifier. 
```suggestion
    asset_subtree_ids: list[dict[Literal["id", "externalId"], int | str]] | None = None
```

2024-08-22 11:45 UTC, doctrino commented on cognite_toolkit/_cdf_tk/client/data_classes/locations.py
> +        )
Subclassing `CogniteObject` gives you this one for free.
```suggestion
```

2024-08-22 11:45 UTC, doctrino commented on cognite_toolkit/_cdf_tk/client/data_classes/locations.py
> +            if resource.get("assets")
Times 5
```suggestion
            if "asset" in resource
```

2024-08-22 11:45 UTC, doctrino commented on cognite_toolkit/_cdf_tk/client/data_classes/locations.py
> +    version: str | None = None
No need to repeat parameters.
```suggestion
```

2024-08-22 11:45 UTC, doctrino commented on cognite_toolkit/_cdf_tk/client/data_classes/locations.py
> +    version: str
Is this to have required `version`? I suggest making a new class and not sublcass DataModelId then.

2024-08-22 11:45 UTC, doctrino commented on cognite_toolkit/_cdf_tk/client/data_classes/locations.py
> +        externalId: The external ID provided by the client. Must be unique for the resource type.
```suggestion
        external_id: The external ID provided by the client. Must be unique for the resource type.
```

2024-08-22 11:45 UTC, doctrino commented on cognite_toolkit/_cdf_tk/client/data_classes/locations.py
> +class LocationFilterAssetCentric:
What about?
```suggestion
class AssetCentricFilter:
```

2024-08-22 11:45 UTC, doctrino commented on cognite_toolkit/_cdf_tk/client/api/locations/api.py
> +        self.location_filters = LocationFiltersAPI(config, api_version, cognite_client)
This becomes `client.locations.locations_filters` I think `client.locations.filters` is better.
```suggestion
        self.filters = LocationFiltersAPI(config, api_version, cognite_client)
```

2024-08-22 11:45 UTC, doctrino commented on cognite_toolkit/_cdf_tk/client/api/locations/location_filters.py
> +            LocationFilter: LocationFilterWrite or list of LocationFilterWrite.
```suggestion
            location_filter: LocationFilterWrite or list of LocationFilterWrite.
```

2024-08-22 11:45 UTC, doctrino commented on cognite_toolkit/_cdf_tk/client/api/locations/location_filters.py
> +        )
I think the client should not invent to much, lets do this in the loader instead.

If the endpoint only supports creating one location at a time, then the client does the same

```suggestion
        res = self._post(url_path=self._RESOURCE_PATH, json=location_filter.dump())
        return LocationFilter._load(res.json(), cognite_client=self._cognite_client)
```

2024-08-22 11:45 UTC, doctrino commented on cognite_toolkit/_cdf_tk/client/api/locations/location_filters.py
> +        raise CogniteNotFoundError(not_found=[external_id])
Move to loader
```suggestion
```

2024-08-22 11:45 UTC, doctrino commented on cognite_toolkit/_cdf_tk/client/api/locations/location_filters.py
> +        return {loc.external_id: loc.id for loc in self.list()}
Move to loader

2024-08-22 11:45 UTC, doctrino commented on cognite_toolkit/_cdf_tk/client/api/locations/location_filters.py
> +        raise CogniteNotFoundError(not_found=[external_id])
Why not implement the actual retrieve endpoint instead?
![image](https://github.com/user-attachments/assets/b605bd79-8c0d-4d31-a3d2-2acd0a338adb)

2024-08-22 11:45 UTC, doctrino commented on cognite_toolkit/_cdf_tk/client/api/locations/location_filters.py
> +        )
Again move support for multiple locations to loader.

2024-08-22 11:45 UTC, doctrino commented on cognite_toolkit/_cdf_tk/client/api/locations/location_filters.py
> +        return n
Same here

2024-08-22 11:45 UTC, doctrino commented on cognite_toolkit/_cdf_tk/client/api/locations/location_filters.py
> +        return LocationFilterList._load(res.json()["items"], cognite_client=self._cognite_client)
There is a method `self._list(...)` that typically we use. It is not necessary as there is no paging for this endpoint, but I would requests that from the backend team

2024-08-22 11:45 UTC, doctrino commented on cognite_toolkit/_cdf_tk/loaders/_resource_loaders/location_loaders.py
> +            return LocationFilterWriteList.load(resources)
This is the same as the parent class, so no need to reimplement it.
```suggestion
```

However, you need to implement it and deal with all the `dataSetId` to `dataSetExternalId` replacements.

2024-08-22 11:45 UTC, doctrino commented on cognite_toolkit/_cdf_tk/loaders/_resource_loaders/location_loaders.py
> +    def get_id(self, item: LocationFilter | LocationFilterWrite | dict) -> str:
```suggestion
    def get_id(cls, item: LocationFilter | LocationFilterWrite | dict) -> str:
```

2024-08-22 11:45 UTC, doctrino commented on cognite_toolkit/_cdf_tk/loaders/_resource_loaders/location_loaders.py
> +        return iter(self.client.locations.location_filters)
In addition, you need to implement `get_write_cls_parameter_spec` and fix all the datasetID issues in the AssetCentric part of the AssetCentric.

2024-08-22 11:45 UTC, doctrino commented on tests/test_unit/approval_client/config.py
> -
This needs to be extended.

2024-08-28 08:57 UTC, doctrino commented on cognite_toolkit/_cdf_tk/client/api/locations/location_filters.py
> +    #     return {loc.external_id: loc.id for loc in self.list()}
```suggestion
```

2024-08-28 08:57 UTC, doctrino commented on cognite_toolkit/_cdf_tk/client/api/locations/location_filters.py
> +
```suggestion
```

2024-08-29 03:43 UTC, doctrino approved these changes
Finished up the PR.

2024-08-29 04:17 UTC, merged